[package]
name = "cubos_sql_e2e"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
cubos_sql = { path = "../cubos_sql" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
rust_decimal = { version = "1", features = ["db-tokio-postgres"] }

[dev-dependencies]
cubos_sql_core = { path = "../cubos_sql_core" }
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "0.7", features = ["with-serde_json-1", "with-chrono-0_4", "with-uuid-1"] }
deadpool-postgres = "0.14"
testcontainers = "0.27"
testcontainers-modules = { version = "0.15", features = ["postgres"] }
libc = "0.2"

[package.metadata.cubos_sql.database]
migrations = "./migrations"

[package.metadata.cubos_sql.domains]
user_preferences = "::cubos_sql_e2e::UserPreferences"

[package.metadata.cubos_sql.enums]
post_status = "::cubos_sql_e2e::PostStatus"
