[package]
name = "pgsafe_cli"
version = "0.1.0"
edition = "2024"
description = "CLI for pgsafe migrations"

[[bin]]
name = "cargo-sql"
path = "src/main.rs"
doc = false

[dependencies]
pgsafe = { path = "../pgsafe" }
pgsafe_core = { path = "../pgsafe_core" }
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
tokio-postgres = "0.7"
postgres-native-tls = "0.5"
native-tls = "0.2"
chrono = "0.4"
dotenvy = "0.15"
