use tokio_postgres::types::ToSql;
use tokio_postgres::Row;

/// Abstraction over types that can execute SQL queries against PostgreSQL.
///
/// You typically do not interact with this trait directly. The [`query!`](crate::query)
/// macro generates code that is generic over `Executor`, so the same query expression
/// works whether you pass a connection pool, a pooled client, a raw client, or a
/// transaction.
///
/// # Implementations
///
/// | Type | Behavior |
/// |------|----------|
/// | `deadpool_postgres::Pool` | Acquires a connection per call, returns it on completion |
/// | `deadpool_postgres::Object` | Delegates to the inner `tokio_postgres::Client` |
/// | `tokio_postgres::Client` | Executes directly on the client |
/// | `tokio_postgres::Transaction<'_>` | Executes within the open transaction |
///
/// # Examples
///
/// Both pool and transaction work transparently:
///
/// ```rust,ignore
/// use cubos_sql::query;
///
/// # async fn example(pool: &deadpool_postgres::Pool) -> Result<(), cubos_sql::Error> {
/// // Using the pool directly
/// let users = query!(pool, "SELECT id, name FROM users").fetch_all().await?;
///
/// // Using a transaction
/// let mut client = pool.get().await.map_err(|e| cubos_sql::Error::Pool(e.to_string()))?;
/// let tx = client.transaction().await?;
/// query!(&tx, "DELETE FROM users WHERE id = $id", id = 1).execute().await?;
/// tx.commit().await?;
/// # Ok(())
/// # }
/// ```
pub trait Executor: Sync {
    /// Executes a query and returns all resulting rows.
    ///
    /// Used internally by the `fetch_all` and `fetch_one`/`fetch_optional` methods
    /// generated by `query!`.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Database`](crate::Error::Database) if the query fails, or
    /// [`Error::Pool`](crate::Error::Pool) if a pooled implementation cannot acquire
    /// a connection.
    fn query<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> impl std::future::Future<Output = Result<Vec<Row>, crate::Error>> + Send + 'a;

    /// Executes a statement and returns the number of affected rows.
    ///
    /// Used internally by the `execute` method generated by `query!` for
    /// `INSERT`, `UPDATE`, and `DELETE` statements.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Database`](crate::Error::Database) if the statement fails, or
    /// [`Error::Pool`](crate::Error::Pool) if a pooled implementation cannot acquire
    /// a connection.
    fn execute<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> impl std::future::Future<Output = Result<u64, crate::Error>> + Send + 'a;
}

impl Executor for tokio_postgres::Client {
    async fn query<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> Result<Vec<Row>, crate::Error> {
        Ok(tokio_postgres::Client::query(self, sql, params).await?)
    }

    async fn execute<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> Result<u64, crate::Error> {
        Ok(tokio_postgres::Client::execute(self, sql, params).await?)
    }
}

impl Executor for tokio_postgres::Transaction<'_> {
    async fn query<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> Result<Vec<Row>, crate::Error> {
        Ok(tokio_postgres::Transaction::query(self, sql, params).await?)
    }

    async fn execute<'a>(
        &'a self,
        sql: &'a str,
        params: &'a [&'a (dyn ToSql + Sync)],
    ) -> Result<u64, crate::Error> {
        Ok(tokio_postgres::Transaction::execute(self, sql, params).await?)
    }
}
