use tokio_postgres::Row;

/// Trait for constructing a type from a `tokio_postgres::Row`.
///
/// Used by the `fetch_*_as::<T>()` methods generated by the `sql!` macro
/// to map query results to user-defined types.
///
/// # Deriving
///
/// Use `#[derive(cubos_sql::FromRow)]` on a struct whose fields match
/// the query's output columns by name:
///
/// ```rust,ignore
/// #[derive(cubos_sql::FromRow)]
/// struct User {
///     id: i64,
///     name: String,
///     email: Option<String>,
/// }
///
/// let user = sql!(pool, "SELECT id, name, email FROM users WHERE id = $id", id = 1)
///     .fetch_one_as::<User>()
///     .await?;
/// ```
///
/// Field names must match column names exactly (or their sanitized form).
/// `Option<T>` fields handle nullable columns automatically.
pub trait FromRow: Sized {
    fn from_row(row: &Row) -> Result<Self, crate::Error>;
}
