//! Proc macro crate for `cubos_sql`.
//!
//! This crate provides the [`sql!`] macro, which performs compile-time
//! verification of SQL queries against a real PostgreSQL schema. Users should
//! depend on the `cubos_sql` crate (which re-exports this macro) rather than
//! depending on `cubos_sql_macros` directly.

extern crate proc_macro;

mod cache;
mod codegen;
mod docker;
mod from_row;
mod introspect;
mod query_macro;

/// Compile-time verified SQL query with named parameters.
///
/// The `sql!` macro lets you write raw SQL with `$named` parameters and get
/// full compile-time type checking. At build time it spins up a PostgreSQL
/// container, runs your migrations, and introspects every query to ensure
/// column names, parameter types, and result types are all correct. The
/// generated code is fully typed -- no runtime reflection, no stringly-typed
/// access.
///
/// # Syntax
///
/// ```text
/// sql!(executor, "SQL text", param1 = value1, param2 = value2, ...)
/// ```
///
/// The full grammar is:
///
/// ```text
/// sql!(
///     <executor>,
///     "<SQL with $param and $..spread { field1, field2 } placeholders>",
///     [name = expr, ...]
/// )
/// .<method>()
/// .await?
/// ```
///
/// - **executor** -- any expression implementing the `cubos_sql::Executor`
///   trait (see [Executor types](#executor-types) below).
/// - **SQL string** -- a string literal containing your SQL. Use `$name` for
///   named parameters and `$..name { fields }` for bulk insert spreads.
/// - **param bindings** (optional) -- zero or more `name = expr` pairs.
///   Parameters referenced in the SQL but not explicitly bound are captured
///   from the surrounding scope.
///
/// # Named parameters
///
/// Use `$name` syntax inside the SQL string to reference parameters. The
/// macro rewrites them to PostgreSQL positional placeholders (`$1`, `$2`, ...)
/// automatically.
///
/// ## Explicit assignment
///
/// ```text
/// sql!(pool, "SELECT * FROM users WHERE id = $user_id", user_id = 42)
/// ```
///
/// ## Scope capture
///
/// If a parameter is not explicitly assigned, the macro captures a variable
/// with the same name from the enclosing scope (similar to closures):
///
/// ```text
/// let min_age = 25;
/// let limit = 10;
/// sql!(pool,
///     "SELECT id, name FROM users WHERE age > $min_age LIMIT $limit"
/// )
/// ```
///
/// ## Deduplication
///
/// When the same `$name` appears multiple times in the SQL, it is
/// deduplicated automatically -- only one value is needed:
///
/// ```text
/// sql!(pool,
///     "SELECT * FROM t WHERE a = $x OR b = $x",
///     x = 42
/// )
/// // Generates: ... WHERE a = $1 OR b = $1
/// ```
///
/// # Return methods
///
/// The macro returns a query builder. Call one of these async methods to
/// execute the query:
///
/// | Method              | Return type          | Description                                     |
/// |---------------------|----------------------|-------------------------------------------------|
/// | `.fetch_all()`      | `Vec<Row>`           | Zero or more rows.                              |
/// | `.fetch_one()`      | `Row`                | Exactly one row. Errors if no rows returned.    |
/// | `.fetch_optional()` | `Option<Row>`        | Zero or one row.                                |
/// | `.execute()`        | `u64`                | Number of rows affected (INSERT/UPDATE/DELETE). |
///
/// `Row` is an anonymous struct generated by the macro with typed fields
/// matching the query's output columns. Your editor's autocomplete will show
/// the available fields and their types.
///
/// ```text
/// // fetch_all -- returns Vec<Row>
/// let users = sql!(pool,
///     "SELECT id, name, email FROM users WHERE age > $min_age",
///     min_age = 25
/// ).fetch_all().await?;
/// // users: Vec<{ id: i64, name: String, email: String }>
///
/// // fetch_one -- returns Row, errors if no rows
/// let user = sql!(pool,
///     "SELECT id, name FROM users WHERE id = $user_id",
///     user_id = 1_i64
/// ).fetch_one().await?;
///
/// // fetch_optional -- returns Option<Row>
/// let maybe_user = sql!(pool,
///     "SELECT id, name FROM users WHERE email = $email",
///     email = "alice@example.com"
/// ).fetch_optional().await?;
///
/// // execute -- returns u64 rows affected
/// let deleted = sql!(pool,
///     "DELETE FROM orders WHERE user_id = $user_id AND total_cents = 0",
///     user_id = 1_i64
/// ).execute().await?;
/// ```
///
/// # Bulk insert with `$..spread`
///
/// The `$..var { field1, field2 }` syntax expands an iterable into multiple
/// `VALUES` rows for bulk inserts. Field mapping is mandatory so the macro
/// knows which struct fields map to which columns.
///
/// ```text
/// let new_users = vec![
///     NewUser { name: "Alice".into(), email: "alice@x.com".into(), age: 30 },
///     NewUser { name: "Bob".into(),   email: "bob@x.com".into(),   age: 25 },
/// ];
///
/// let inserted = sql!(pool,
///     "INSERT INTO users (name, email, age)
///      VALUES $..new_users { name, email, age }
///      RETURNING id, name"
/// ).fetch_all().await?;
/// // Generates: VALUES ($1,$2,$3), ($4,$5,$6)
/// // inserted: Vec<{ id: i64, name: String }>
/// ```
///
/// You can select a subset of fields or reorder them:
///
/// ```text
/// // Only insert name and email (age gets DEFAULT)
/// sql!(pool,
///     "INSERT INTO users (name, email) VALUES $..new_users { name, email }"
/// ).execute().await?;
/// ```
///
/// Multiple spreads are supported (e.g. in CTEs):
///
/// ```text
/// sql!(pool,
///     "WITH a AS (INSERT INTO t1 VALUES $..items_a { x, y } RETURNING id),
///          b AS (INSERT INTO t2 VALUES $..items_b { z } RETURNING id)
///      SELECT * FROM a, b"
/// ).fetch_all().await?;
/// ```
///
/// # Domain types (JSONB)
///
/// Columns defined with `CREATE DOMAIN ... AS JSONB` are automatically
/// deserialized into the corresponding Rust struct, and parameters with
/// domain types are automatically serialized. The mapping is configured in
/// your `Cargo.toml`:
///
/// ```text
/// [package.metadata.cubos_sql.domains]
/// user_preferences = "crate::domains::UserPreferences"
/// order_metadata = "crate::domains::OrderMetadata"
/// ```
///
/// With this configuration, reading a `user_preferences` column returns a
/// `UserPreferences` struct directly, and passing a `UserPreferences` value
/// as a parameter serializes it to JSONB automatically:
///
/// ```text
/// // Reading: preferences is deserialized to UserPreferences
/// let user = sql!(pool,
///     "SELECT id, preferences FROM users WHERE id = $id",
///     id = 1_i64
/// ).fetch_one().await?;
/// println!("theme: {}", user.preferences.theme);
///
/// // Writing: prefs is serialized to JSONB automatically
/// let prefs = UserPreferences { theme: "dark".into(), locale: "en".into(), notifications: true };
/// sql!(pool,
///     "UPDATE users SET preferences = $prefs WHERE id = $user_id",
///     user_id = 1_i64
/// ).execute().await?;
/// ```
///
/// The Rust struct must implement `serde::Serialize` (for parameters) and/or
/// `serde::Deserialize` (for output columns).
///
/// # Executor types
///
/// The first argument to `sql!` can be any type implementing
/// `cubos_sql::Executor`:
///
/// - `deadpool_postgres::Pool` (or `&Pool`)
/// - `deadpool_postgres::Object` (a checked-out connection)
/// - `tokio_postgres::Client`
/// - `tokio_postgres::Transaction<'_>`
///
/// This means you can pass a pool for simple queries, or a transaction when
/// you need atomicity:
///
/// ```text
/// let tx = pool.begin().await?;
/// sql!(tx, "INSERT INTO orders (...) VALUES (...)").execute().await?;
/// sql!(tx, "UPDATE users SET ...").execute().await?;
/// tx.commit().await?;
/// ```
///
/// # Compile-time behavior
///
/// When you run `cargo build`, each `sql!` invocation triggers the
/// following pipeline:
///
/// 1. **Configuration** -- reads `[package.metadata.cubos_sql]` from your
///    `Cargo.toml` to find migration paths, Docker image, and domain
///    mappings.
/// 2. **Docker container** -- hashes your migration files. If the hash
///    matches a cached container, it is reused. Otherwise, a new PostgreSQL
///    container is started and migrations are applied.
/// 3. **Query introspection** -- the SQL is sent to PostgreSQL via `PREPARE`,
///    and `pg_catalog` is queried to determine parameter types, output column
///    types, and nullability.
/// 4. **Code generation** -- an anonymous output struct and a typed query
///    builder are generated as Rust code.
/// 5. **Caching** -- introspection results are cached in a `.cubos_sql/`
///    directory (which should be added to `.gitignore`) to avoid redundant
///    work on subsequent builds.
///
/// # Compile-time errors
///
/// The macro produces clear compile-time errors when something is wrong:
///
/// ```text
/// // Invalid column name
/// sql!(pool, "SELECT nonexistent FROM users").fetch_all().await?;
/// // error: column "nonexistent" does not exist in table "users"
///
/// // Type mismatch
/// let age: &str = "not a number";
/// sql!(pool, "SELECT id FROM users WHERE age > $age").fetch_all().await?;
/// // error: expected INT, got &str
///
/// // Missing field mapping on spread
/// sql!(pool, "INSERT INTO users (name, email) VALUES $..items");
/// // error: $..items requires explicit field mapping: $..items { field1, field2 }
/// ```
#[proc_macro]
pub fn sql(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input = syn::parse_macro_input!(input as query_macro::QueryInput);
    match query_macro::expand(input) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

/// Derive macro for `cubos_sql::FromRow`.
///
/// Generates an implementation that constructs the struct from a
/// `tokio_postgres::Row` by extracting each field by column name.
///
/// ```rust,ignore
/// #[derive(cubos_sql::FromRow)]
/// struct User {
///     id: i64,
///     name: String,
///     email: Option<String>,
/// }
/// ```
#[proc_macro_derive(FromRow)]
pub fn derive_from_row(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input = syn::parse_macro_input!(input as syn::DeriveInput);
    match from_row::expand(input) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}
